### PR TITLE
Add ability to rebuild zelnode db from rpc

### PR DESCRIPTION
**Pull request by blondfrogs**

### CODE REVIEW

**Comment by TheTrunk** [comment]
@blondfrogs Is this still all ok for merging?

**Comment by blondfrogs** [comment]
> @blondfrogs Is this still all ok for merging?

yes, it should be.

**Comment by TheTrunk** [comment]
tACK
Note: While doing rebuild of database, any calls to zelcash will just hang not responding with any error message.

**Comment by TheTrunk** [comment]
Furthermore zelcash fails to sync further after rebuild command, marking blockheaders as invalid. Says invalid chain found due to bad zelnode payees in the coinbase.

**Review by TheTrunk — APPROVED** [review]
Command works well. Just takes hours to finish which is expacted.
Running with debug flux I have tons of these lines:
2021-11-03 06:56:26 CheckForExpiredStartTx : Size of mapStartTxTracker: 2
2021-11-03 06:56:26 CheckForExpiredStartTx : Size of mapStartTxDosTracker: 6
2021-11-03 06:56:26 CheckForExpiredStartTx : Size of mapConfirmedZelnodeData: 744
Bench debug gives correct expectations.
tack 👍

**Comment by Cabecinha84** [comment]
Ack

**Review by Cabecinha84 — APPROVED** [review]
Ack!

**Pull request merged**
