### PR TITLE
Release v6.1.0

### PR DESCRIPTION
**Pull request by TheTrunk**

### CODE REVIEW

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Comment by TheTrunk** [comment]
looks like building is broken for amr/amd

**Comment by TheTrunk** [comment]
make[1]: *** No rule to make target 'zelcashd.1', needed by 'all-am'.  Stop.

**Comment by Cabecinha84** [comment]
Does it still build zelcashd, weren't the bins changed to fluxd? Maybe there is missed reference to be changed to fluxd.

**Pull request closed without merging**
