### PR TITLE
Add ability to create snapshots

### PR DESCRIPTION
**Pull request by blondfrogs**
This code adds a new database in a new folder /snapshots
New RPC call **printsnapshot \<timestamp\>**

To take a snapshot add the following to the .conf 
snapshot=\<timestamp\>

or run fluxd with the flag 
-snapshot=\<timestamp\>

The snapshot will be taken on the block height of the next block that comes after the given \<timestamp\>

Example: 
snapshot=1649783322 which is (Tue Apr 12 2022 17:08:42 UTC)

Give the following snapshot: 
` {
  "nTime": 1649783322,
  "height": 1097936,
  "balances": {
    "t1Hsc324kffbMX2ehmSMHLB2JBxLn8E76EL": 142.57974269,
    "t1HscB7BresscYibF5hiAzotugpnEwAgxki": 0.00200000,
    "t1HscB7DDYqKHLXWipvZ7pmmxE1VFPXW5b4": 0.00185900,
    "t1HscCUEEMpGtdQzXedWwuc614U7wHiG4JQ": 0.00080000,
    ............
    ............
}`

The height 1097936 - has the timestamp of 1649783340, which is 18 seconds after the given timestamp. 

To produce the snapshot into a readable format. Call the following rpccall

`printsnapshot  <timestamp>  >> snapshot.json`

Then open snapshot.json to view the snapshot data

### CODE REVIEW

**Comment by TheTrunk** [comment]
tACK, works amazing. 
- Sum of balances matches expected. 
- Produces reliable results - different nodes produced same snapshot
- On a given set of addresses, balance obtained was same as expected balance

**Review by TheTrunk — APPROVED** [review]

**Review by Cabecinha84 — APPROVED** [review]
Ack.
- wouldn't make more sense to use block height instead of timestamp?

**Comment by TheTrunk** [comment]
> Ack.
> 
> * wouldn't make more sense to use block height instead of timestamp?

Timestamp is actually better for us as we can prepare everything more in advance :)

**Comment by blondfrogs** [comment]
@TheTrunk @Cabecinha84 Now you can use either height or timestamp to perform a snapshot

**Pull request merged**
