### PR TITLE
added own servers

### PR DESCRIPTION
**Pull request by XK4MiLX**

### CODE REVIEW

**Review by Cabecinha84 — COMMENTED** [review]
isn't https?
Will this work for chinese community? Despite most probably they had a workaround already for the z.cash.

**Comment by Cabecinha84** [comment]
@TheTrunk @blondfrogs this should be merged first, before p2shnodes branch is merged to master.

**Comment by XK4MiLX** [comment]
> isn't https? Will this work for chinese community? Despite most probably they had a workaround already for the z.cash.

https is not support for majority of cdns

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Comment by TheTrunk** [comment]
From chat discussion:

> Can we figure out some better cdn?
> Like having just https://cdn.runonflux.io/ ?
> I think that would be more elegant
> https://cdn.runonflux.io/downloads and having just the params there. In the backend it will be load balanced to some servers? or would use cloudflare cdn for caching and we would store the files under the limit
> I think z.cash uses cloudflare cdn too for caching the parameters and thats why they are splitted to multiple small files
> as cloudflare only allow under some size

I think we can set this up in the next days

**Comment by TheTrunk** [comment]
Replaced by #228

**Pull request closed without merging**
